export enum OverlayEnum {
  datePicker = 'datePicker',
  timePicker = 'timePicker',
  tagEditor = 'tagEditor',
  popupAction = 'popupAction',
  dialog = 'dialog',
  toast = 'toast',
  taskDisplaySettings = 'taskDisplaySettings',
  projectAreaSelector = 'projectAreaSelector',
  desktopMenu = 'desktopMenu',
  desktopDatePicker = 'desktopDatePicker',
  desktopTimePicker = 'desktopTimePicker',
  desktopTagEditor = 'desktopTagEditor',
  message = 'message',
  createDatabase = 'createDatabase',
  treeSelect = 'treeSelect',
  desktopRecurringTaskSettings = 'desktopRecurringTaskSettings',
}
