export const baseStyles = {
  homeMenuBackground: /*tw*/ 'bg-bg1',
  homeMenuRound: /*tw*/ 'rounded-md',
  homeMenuItemPadding: /*tw*/ 'px-3 py-2',
  homePageItemGap: /*tw*/ 'gap-2',
  homeMenuNumberColor: /*tw*/ 'text-sm font-medium text-t3',
  homeMenuDueTaskNumberColor: /*tw*/ 'text-sm font-medium text-white bg-accent-danger rounded-full h-4 min-w-4',
  homeMenuIconStyle: /*tw*/ 'w-5 h-5 text-brand',

  statCardContainer: /*tw*/ 'grid grid-cols-2 gap-3',
  statCardRoot: /*tw*/ 'px-4 pt-4.5 pb-4 flex flex-col gap-3.5 ui-card-glass',
  statCardHeader: /*tw*/ 'flex justify-between items-start',
  statCardIconContainer: /*tw*/ 'size-9 rounded-xl flex items-center justify-center',
  statCardIcon: /*tw*/ 'size-4.5',
  statCardCountContainer: /*tw*/ 'flex items-baseline gap-2 text-xl font-semibold',
  statCardOverdueCount: /*tw*/ 'text-accent-danger',
  statCardCount: /*tw*/ 'text-t2',
  statCardLabel: /*tw*/ 'text-sm text-t2',

  screenEdgePadding: /*tw*/ 'px-4',

  bottomMenuHeight: /*tw*/ 'h-11',
  bottomMenuBorder: /*tw*/ 'border-t border-line-light',
  bottomMenuTextNormal: /*tw*/ 'text-t2',
  bottomMenuTextActive: /*tw*/ 'text-brand',
  bottomMenuTextInactive: /*tw*/ 'text-t3',

  listItemRound: /*tw*/ '',
  listItemDraggedBackground: /*tw*/ 'bg-bg3',

  pageBackground: /*tw*/ 'bg-bg2',
  pageLayoutRoot: /*tw*/ 'polyfill-min-h-dvh min-h-dvh text-t1',
  pageLayoutSafeTop: /*tw*/ 'safe-top',
  pageLayoutHeaderPlaceholder: /*tw*/ 'sticky top-0 z-100 safe-top',
  pageLayoutHeaderContainer: /*tw*/ 'top-0 z-100',
  pageLayoutSticky: /*tw*/ 'sticky',
  pageLayoutMetaSpacing: /*tw*/ 'mb-6',
  pageLayoutSafeBottom: /*tw*/ 'safe-bottom',
  pageLayoutKeyboardSpacer: /*tw*/ 'h-[var(--keyboard-height)] w-full',
  listItemBackground: /*tw*/ 'bg-bg1',
  listItemEditingBackground: /*tw*/ 'bg-bg1',

  itemRound: /*tw*/ 'rounded-md',

  headerBackground: /*tw*/ 'bg-bg2',
  headerRoot: /*tw*/ 'w-full h-15 px-5 py-3 relative',
  headerLeftContainer: /*tw*/ 'flex gap-2 absolute left-5.5 top-1/2 -translate-y-1/2',
  headerRightContainer: /*tw*/ 'flex gap-2 absolute right-5 top-1/2 -translate-y-1/2',
  headerTitle: /*tw*/ 'text-base font-medium text-t1 absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2',
  headerActionButton:
    /*tw*/ 'size-9 flex items-center justify-center border-none bg-bg1 cursor-pointer rounded-full text-t2',
  headerActionButtonIcon: /*tw*/ 'size-5 flex items-center justify-center',

  taskItemGroupRound: /*tw*/ 'rounded-2xl',
  taskItemGroupBackground: /*tw*/ 'bg-bg1',
  taskItemGroupHeaderPadding: /*tw*/ 'pt-3',
  taskItemGroupTopRound: /*tw*/ 'rounded-t-2xl',
  taskItemGroupBottomRound: /*tw*/ 'rounded-b-2xl',
  taskItemGroupSpacing: /*tw*/ 'mb-3',
  taskItemGroupHeader: /*tw*/ 'flex items-baseline gap-3 py-3',
  taskItemGroupTitle: /*tw*/ 'text-xl font-medium text-t1 leading-none',
  taskItemGroupSubtitle: /*tw*/ 'text-sm text-t3',

  taskItemGroupPaddingBottomWhenDragging: /*tw*/ 'pb-11',

  taskItemRoot: /*tw*/ 'flex items-start',
  taskItemHeight: /*tw*/ 'min-h-[3.25rem] py-3.5',
  taskItemPaddingX: /*tw*/ 'px-4',
  taskItemPlaceholderColor: /*tw*/ 'text-t3',
  taskItemGap: /*tw*/ 'gap-3',
  taskItemIconSize: /*tw*/ 'h-6 w-6 flex-shrink-0 flex items-center justify-center text-t3',
  taskItemContent: /*tw*/ 'flex-1 flex flex-col gap-1 min-w-0',
  taskItemTitleRow: /*tw*/ 'flex items-center gap-2 min-w-0',
  taskItemArchived: /*tw*/ 'opacity-50!',

  taskItemEditingRound: /*tw*/ 'rounded-2xl',
  taskItemEditingShadow: /*tw*/ '',

  taskItemOverlayBackground: /*tw*/ 'bg-bg1',
  taskItemOverlayRound: /*tw*/ 'rounded-2xl',
  taskItemOverlayShadow: /*tw*/ 'inset-shadow-sm shadow-sm',

  taskItemDraggingRound: /*tw*/ 'rounded-2xl',

  pageContentPaddingX: /*tw*/ 'px-4',
  pageContentPaddingY: /*tw*/ 'pb-15',
  pageContentColumn: /*tw*/ 'flex flex-col',
  pageEmptyState: /*tw*/ 'flex h-100 items-center justify-center text-t3',
  pageStateRoot: /*tw*/ 'flex flex-col items-center justify-center py-12 text-center',
  pageStateLabel: /*tw*/ 'mb-6 px-4 text-sm text-t2',
  pageStateLink: /*tw*/ 'text-brand text-sm font-medium transition-colors hover:text-brand/80',

  overlayBackground: /*tw*/ 'bg-black',
  overlayBackgroundOpacity: /*tw*/ 'opacity-50',
  overlayAnimationDuration: /*tw*/ 'duration-250',
  actionSheetPadding: /*tw*/ 'p-4 pt-0',
  actionSheetRound: /*tw*/ 'rounded-t-[20px]',
  actionSheetBorder: /*tw*/ '',
  actionSheetBackground: /*tw*/ 'bg-bg2',

  actionSheetActionGroupRound: /*tw*/ 'rounded-lg',
  actionSheetActionGroupBackground: /*tw*/ 'bg-bg1',
  actionSheetActionGroupItemPadding: /*tw*/ 'p-4',
  actionSheetActionGroupItemGap: /*tw*/ 'gap-2',
  actionSheetContentBorder: /*tw*/ '',
  actionSheetPosition: /*tw*/ 'absolute left-0 bottom-0 right-0 transition-transform safe-bottom',
  actionSheetHandleContainer: /*tw*/ 'flex items-center justify-center pt-3 pb-2',
  actionSheetHandleBar: /*tw*/ 'w-10 h-1 bg-t4 rounded-full',
  actionSheetContentOverflow: /*tw*/ 'overflow-y-auto',
  actionSheetRoot: /*tw*/ 'fixed inset-0 text-t1',
  overlayBackdrop: /*tw*/ 'absolute inset-0 transition-opacity',
  overlayHidden: /*tw*/ 'opacity-0',

  tagEditorContainerBackground: /*tw*/ 'bg-bg1',
  tagEditorSelectedTagColor: /*tw*/ 'text-brand',
  tagEditorInputTextColor: /*tw*/ 'text-t1',
  tagEditorSuggestionBackground: /*tw*/ 'bg-bg1',
  tagEditorSuggestionTextColor: /*tw*/ 'text-t1',
  tagEditorCreateTagTextColor: /*tw*/ 'text-brand',
  tagEditorContainerPadding: /*tw*/ 'px-4 py-2',
  tagEditorContainerRound: /*tw*/ 'rounded-lg',
  tagEditorSuggestionPadding: /*tw*/ 'px-4 py-2',
  tagEditorSuggestionRound: /*tw*/ 'rounded-lg',
  tagEditorTextSize: /*tw*/ 'text-sm',
  tagEditorSmallGap: /*tw*/ 'gap-2',
  tagEditorHeightDefault: /*tw*/ 'h-11',
  tagEditorMinHeightDefault: /*tw*/ 'min-h-11',

  datePickerDayCellHeight: /*tw*/ '56',
  datePickerMonthHeaderHeight: /*tw*/ '40',
  datePickerGapHeight: /*tw*/ '4',
  datePickerItemHeight: /*tw*/ '0',
  datePickerDayButtonHeight: /*tw*/ 'h-14',
  datePickerDayButtonRound: /*tw*/ 'rounded-lg',
  datePickerDayButtonBase: /*tw*/ 'text-sm relative',
  datePickerDaySelectedBackground: /*tw*/ 'bg-brand',
  datePickerDaySelectedTextColor: /*tw*/ 'text-white',
  datePickerDayButtonSelected: /*tw*/ 'bg-brand text-white',
  datePickerTodayTextColor: /*tw*/ 'text-brand',
  datePickerTodayLabel: /*tw*/ 'absolute top-0 left-0 w-full h-full flex items-start justify-center text-xs pt-1',
  datePickerHeaderBackground: /*tw*/ 'bg-bg3',
  datePickerHeaderPadding: /*tw*/ 'py-2 px-4',
  datePickerWeekdayTextColor: /*tw*/ 'text-t1',
  datePickerWeekdayTextSize: /*tw*/ 'text-sm',
  datePickerBackground: /*tw*/ 'bg-bg1!',
  datePickerContentPadding: /*tw*/ 'px-4',
  datePickerTitlePadding: /*tw*/ 'px-2',
  datePickerActionSheetPadding: /*tw*/ 'px-0!',

  fabButton: /*tw*/ 'size-14 bg-brand rounded-full flex items-center justify-center z-[1000] text-white',

  taskDetailBottomActionStyle: /*tw*/ 'flex items-center justify-center size-9 rounded-lg  text-t2',
  taskDetailBottomActionIconStyle: /*tw*/ 'size-5',

  // Project Info styles (matches Vue Info component)
  projectInfoRoot: /*tw*/ 'ui-card-glass flex items-start gap-3 px-4 py-3.5',
  projectInfoLogoContainer: /*tw*/ 'size-6 flex items-center justify-center shrink-0',
  projectInfoContent: /*tw*/ 'flex-1 min-w-0 gap-2 flex flex-col',
  projectInfoTitle:
    /*tw*/ 'w-full text-lg leading-6 font-medium text-t1 bg-transparent border-none outline-none resize-none p-0',
  projectInfoAttrRow: /*tw*/ 'flex items-start gap-1.5',
  projectInfoAttrIconContainer: /*tw*/ 'h-6 flex items-center justify-center shrink-0 text-t3',
  projectInfoAttrContent: /*tw*/ 'flex-1 min-w-0 flex',
  projectInfoMetaIcon: /*tw*/ 'size-4',
  projectInfoSection: /*tw*/ 'flex flex-col gap-2',
  areaMetaIcon: /*tw*/ 'size-5.5 text-t2',

  infoItemRound: /*tw*/ 'rounded-md',
  infoItemPadding: /*tw*/ 'py-1.5 px-2',
  infoItemMargin: /*tw*/ 'mb-1.5',
  infoItemGap: /*tw*/ 'gap-2',
  infoItemIconColor: /*tw*/ 'text-t2',
  infoItemTextColor: /*tw*/ 'text-t1',
  infoItemDeleteIconColor: /*tw*/ 'text-t3',
  infoItemIconSize: /*tw*/ 'size-4',
  infoItemTextSize: /*tw*/ 'text-sm',
  infoItemDeleteIconSize: /*tw*/ 'size-4',
  infoItemGroupGap: /*tw*/ 'gap-0',
  infoItemGroupBackground: /*tw*/ 'bg-bg1',
  infoItemGroupRound: /*tw*/ 'rounded-lg',
  infoItemBaselineRow: /*tw*/ 'flex items-baseline gap-2',
  infoItemInlineRow: /*tw*/ 'flex items-center gap-2',
  attrContentWithClear: /*tw*/ 'flex w-full items-center justify-between',
  attrLabelTitle: /*tw*/ 'text-sm leading-6',
  attrLabelSubtitle: /*tw*/ 'text-sm text-t2',
  itemItemMinHeight: /*tw*/ 'min-h-10',
  editingTaskSubtaskContainerBackground: /*tw*/ 'bg-bg2',
  editingTaskSubtaskPadding: /*tw*/ 'px-2',
  editingTaskSubtaskContainerRound: /*tw*/ 'rounded-lg',
  editingTaskSubtaskContainerMargin: /*tw*/ 'mb-2 mt-1.5',
  editingTaskSubtaskContainerSpacing: /*tw*/ 'space-y-0.5',
  editingTaskSubtaskOverlay: /*tw*/ 'px-2 bg-bg2',
  editingTaskSubtaskHeader: /*tw*/ 'flex items-center gap-2 text-t2 text-sm leading-6 ml-1',
  editingTaskSubtaskProgressBar: /*tw*/ 'w-12 h-2 bg-bg3 rounded-full overflow-hidden',
  editingTaskSubtaskProgressFill: /*tw*/ 'h-full bg-brand rounded-full',
  editingTaskSubtaskList: /*tw*/ 'flex-1 flex flex-col gap-1 min-w-0 -ml-1',
  editTaskItemRootPaddingY: /*tw*/ 'py-3.5',
  editTaskItemContent: /*tw*/ 'flex-1 min-w-0 flex flex-col gap-1',
  editTaskItemTitleInputRow: /*tw*/ 'flex items-center gap-2 min-w-0',
  editTaskItemTitleInput:
    /*tw*/ 'min-w-0 overflow-hidden text-ellipsis text-base leading-6 font-medium text-t1 bg-transparent outline-none w-full',
  editTaskItemStatusButton: /*tw*/ 'size-6 shrink-0 flex items-center justify-center text-t3',
  editTaskItemMenuButton: /*tw*/ 'size-6 shrink-0 flex items-center justify-end text-t3',
  editTaskItemExpanded: /*tw*/ 'grid grid-rows-[1fr]',
  editTaskItemExpandedOverflow: /*tw*/ 'overflow-hidden',
  editTaskItemExpandedRow: /*tw*/ 'flex gap-3 mt-2',
  editTaskItemExpandedSpacer: /*tw*/ 'size-6 shrink-0 -ml-0.5',
  editTaskItemExpandedContent: /*tw*/ 'flex-1 min-w-0 flex flex-col gap-1',

  // Edit Task - AttrRow styles (matches Vue TaskAttr)
  editTaskAttrRow: /*tw*/ 'flex items-start gap-2',
  editTaskAttrIconContainer: /*tw*/ 'h-6 w-4 flex items-center justify-center shrink-0 text-t3',
  editTaskAttrContent: /*tw*/ 'flex-1 min-w-0 flex',
  editTaskAttrIcon: /*tw*/ 'size-4',

  // Create Task - Card & AttrRow styles
  createTaskCardRoot: /*tw*/ 'ui-card-glass flex flex-col gap-3 p-4',
  createTaskAttrRow: /*tw*/ 'flex items-start gap-3',
  createTaskAttrIconContainer: /*tw*/ 'h-6 w-5 flex items-center justify-center shrink-0 text-t3',
  createTaskAttrIcon: /*tw*/ 'size-4',
  createTaskAttrContent: /*tw*/ 'flex-1 min-w-0 flex w-full',
  createTaskAttrPlaceholder: /*tw*/ 'text-sm leading-6 text-t4 cursor-pointer',
  createTaskTitleInput:
    /*tw*/ 'w-full text-lg font-medium text-t1 placeholder:text-t4 bg-transparent border-none outline-none p-0',
  createTaskNotesTextarea:
    /*tw*/ 'w-full text-sm leading-6 text-t2 bg-transparent border-none outline-none resize-none p-0 placeholder:text-t4',
  createTaskTagsContainer: /*tw*/ 'flex flex-wrap gap-2',
  createTaskTag:
    /*tw*/ 'text-xs leading-6 h-6 text-brand font-medium bg-bg4 rounded-full px-2 flex items-center justify-center',
  createTaskSubtaskHeader: /*tw*/ 'flex items-center gap-2 text-t2 text-sm leading-6 ml-1',
  createTaskSubtaskProgressBar: /*tw*/ 'w-12 h-2 bg-bg3 rounded-full overflow-hidden',
  createTaskSubtaskProgressFill: /*tw*/ 'h-full bg-brand rounded-full',
  createTaskSubtaskList: /*tw*/ 'flex flex-col gap-1 w-full',
  createTaskSubtaskItem: /*tw*/ 'flex items-center gap-2 -ml-1',
  createTaskSubtaskItemIcon: /*tw*/ 'text-t3',
  createTaskSubtaskInput:
    /*tw*/ 'flex-1 text-sm leading-6 text-t1 bg-transparent border-none outline-none p-0 placeholder:text-t4',
  createTaskSubtaskDragHandle: /*tw*/ 'size-4 cursor-grab text-t3 opacity-40',
  createTaskAddButton: /*tw*/ 'text-sm leading-6 text-t4 cursor-pointer text-left',
  subtaskItemDraggingPlaceholder: /*tw*/ 'flex items-center gap-1.5 bg-bg3 rounded-lg w-full',
  subtaskItemRoot: /*tw*/ 'flex items-center gap-1.5',
  subtaskItemStatusButton: /*tw*/ 'flex items-center justify-center text-t3',
  subtaskItemInputCompleted: /*tw*/ 'text-t3',
  subtaskItemInputCanceled: /*tw*/ 'text-t3 line-through',
  subtaskItemInputNormal: /*tw*/ 'text-t1',
  createTaskReminderItem: /*tw*/ 'flex items-center justify-between',
  createTaskReminderText: /*tw*/ 'flex-1 min-w-0 border-none bg-transparent p-0 text-left text-t2',
  createTaskReminderContent: /*tw*/ 'flex items-baseline gap-2',
  createTaskReminderTitle: /*tw*/ 'text-sm leading-6 text-t1',
  createTaskReminderSubtitle: /*tw*/ 'text-sm text-t2',
  createTaskReminderRemoveBtn:
    /*tw*/ 'size-4 flex items-center justify-center border-none bg-transparent p-0 text-t4 cursor-pointer',
  createTaskRemoveIcon: /*tw*/ 'size-4 cursor-grab text-t3 opacity-40',

  inputItemStyle: /*tw*/ 'bg-bg1 rounded-lg focus:outline-none px-3 py-2 w-full border-0 text-base',
  textAreaItemStyle: /*tw*/ 'bg-bg1 rounded-lg focus:outline-none px-3 py-2 w-full border-0 text-sm',
  itemEditTaskNotesTextAreaStyle:
    /*tw*/ 'bg-bg1 rounded-lg focus:outline-none px-0 py-0 w-full border-0 text-sm text-t2',

  createTaskPageStyle: /*tw*/ 'min-h-dvh w-full bg-bg2 text-t1 safe-top',

  tabbarBackground: /*tw*/ 'bg-bg1',
  tabbarHeight: /*tw*/ 'h-10',
  tabbarRound: /*tw*/ 'rounded-lg',
  tabbarItemWidth: /*tw*/ 'w-24',
  tabbarItemTextSize: /*tw*/ 'text-sm',
  tabbarItemTextColorActive: /*tw*/ 'text-brand',
  tabbarItemTextColorInactive: /*tw*/ 'text-t2',
  tabbarItemFontWeight: /*tw*/ 'font-medium',
  tabbarIndicatorWidth: /*tw*/ 'w-4',
  tabbarIndicatorHeight: /*tw*/ 'h-0.5',
  tabbarIndicatorMarginTop: /*tw*/ 'mt-1',
  tabbarIndicatorRound: /*tw*/ 'rounded-full',
  tabbarIndicatorColorActive: /*tw*/ 'bg-brand',
  tabbarIndicatorColorInactive: /*tw*/ 'bg-transparent',

  projectAreaSelectorContainer: /*tw*/ 'h-50 overflow-y-scroll flex flex-col space-y-2',
  projectAreaSelectorInputContainer: /*tw*/ 'bg-bg1 rounded-md px-3 py-2 text-t1 h-11 w-full flex items-center',
  projectAreaSelectorInput: /*tw*/ 'flex-1 min-w-40 focus:outline-none bg-transparent text-sm',
  projectAreaSelectorItem:
    /*tw*/ 'bg-bg1 rounded-md px-3 py-2 text-t1 break-words w-full text-left flex items-center gap-2',
  projectAreaSelectorItemIcon: /*tw*/ 'size-5 text-t3',
  projectAreaSelectorSubItemPadding: /*tw*/ 'pl-4',
  projectAreaSelectorTextSize: /*tw*/ 'text-sm',
  projectAreaSelectorContentGap: /*tw*/ 'space-y-2',
  projectAreaSelectorDisabled: /*tw*/ 'opacity-50',

  switchUncheckedBackground: /*tw*/ 'bg-bg2',
  switchCheckedBackground: /*tw*/ 'bg-brand',
  switchInnerBorder: /*tw*/ '',
  switchOuterBorder: /*tw*/ '',

  dialogBorder: /*tw*/ '',
  dialogOverlayRoot: /*tw*/ 'fixed inset-0 flex items-center justify-center',
  dialogBackdrop: /*tw*/ 'absolute inset-0',
  dialogPanel: /*tw*/ 'bg-bg1 rounded-lg flex flex-col w-80 absolute max-h-[80vh] overflow-y-auto',
  dialogBody: /*tw*/ 'flex flex-col p-6 space-y-4',
  dialogDescription: /*tw*/ 'text-sm text-center text-t2 whitespace-pre-line',
  dialogActionList: /*tw*/ 'space-y-4',
  dialogFieldLabel: /*tw*/ 'block text-sm font-medium text-t1 mb-2',
  dialogRequiredMark: /*tw*/ 'text-accent-danger ml-1',
  dialogInput: /*tw*/ 'w-full px-3 py-2 border bg-bg2 rounded-md text-t1 outline-none transition-colors',
  dialogInputNormal: /*tw*/ 'border-bg2 focus:border-brand',
  dialogInputError: /*tw*/ 'border-accent-danger',
  dialogInputLightBorder: /*tw*/ 'border-line-light',
  dialogInputPlaceholder: /*tw*/ 'placeholder-t3',
  dialogFieldError: /*tw*/ 'text-xs text-accent-danger mt-1',
  dialogFieldHelp: /*tw*/ 'mt-2 text-sm text-t2',
  dialogFieldAccent: /*tw*/ 'mt-2 text-sm text-brand',
  dialogButton: /*tw*/ 'w-full py-2 px-4 rounded-md text-center font-medium',
  dialogButtonPrimary: /*tw*/ 'bg-brand text-white',
  dialogButtonDanger: /*tw*/ 'bg-accent-danger text-white',
  dialogButtonDefault: /*tw*/ 'bg-bg2 text-t1',
  dialogTitle: /*tw*/ 'text-lg font-medium text-center text-t1',
  dialogFooter: /*tw*/ 'border-t border-bg1 rounded-b-lg',
  dialogFooterInner: /*tw*/ 'flex flex-row justify-center items-center h-full px-4',
  dialogFooterButton: /*tw*/ 'flex-1 text-base text-center',
  dialogFooterCancelButton: /*tw*/ 'text-t1',
  dialogFooterConfirmEnabled: /*tw*/ 'text-brand',
  dialogFooterConfirmDisabled: /*tw*/ 'text-t3',

  // SettingsListItem styles
  settingsListItemRoot:
    /*tw*/ 'flex items-center justify-between py-3.5 px-4 cursor-pointer transition-colors duration-200',
  settingsListItemIconContainer: /*tw*/ 'mr-4 shrink-0 size-6',
  settingsListItemIconDanger: /*tw*/ 'text-accent-danger',
  settingsListItemIconNormal: /*tw*/ 'text-t2',
  settingsListItemContent: /*tw*/ 'flex flex-col gap-0.5 flex-1 min-w-0',
  settingsListItemTitle: /*tw*/ 'text-base font-medium',
  settingsListItemTitleDanger: /*tw*/ 'text-accent-danger',
  settingsListItemTitleNormal: /*tw*/ 'text-t1',
  settingsListItemDescription: /*tw*/ 'text-xs text-t2',
  settingsListItemCheckContainer: /*tw*/ 'size-5 flex items-center justify-center',
  settingsListItemCheckIcon: /*tw*/ 'text-brand',
  settingsListItemCheckIconSize: /*tw*/ 'size-4.5',
  settingsListItemNavContainer: /*tw*/ 'flex items-center',
  settingsListItemNavLabel: /*tw*/ 'text-xs text-t3 mr-1',
  settingsListItemNavIcon: /*tw*/ 'size-4 text-t3',
  settingsListItemLabelText: /*tw*/ 'text-xs text-t3',
  settingsListItemButtonRoot: /*tw*/ 'flex items-center py-3 px-4 cursor-pointer transition-colors duration-200',
  settingsListItemButtonAlignLeft: /*tw*/ 'justify-start',
  settingsListItemButtonAlignRight: /*tw*/ 'justify-end',
  settingsListItemButtonAlignCenter: /*tw*/ 'justify-center',
  settingsListItemButtonText: /*tw*/ 'text-base font-medium',
  settingsListItemButtonTextDanger: /*tw*/ 'text-accent-danger',
  settingsListItemButtonTextPrimary: /*tw*/ 'text-brand',

  // SettingsListGroup styles
  settingsListGroupRoot: /*tw*/ 'flex flex-col w-full',
  settingsListGroupTitle: /*tw*/ 'text-sm text-t2 ml-4 pb-3',
  settingsListGroupContainer: /*tw*/ 'flex flex-col rounded-2xl overflow-hidden bg-bg1',
  settingsListGroupSubtitle: /*tw*/ 'text-xs text-t3 ml-4 pt-2',
  settingsListGroupDivider: /*tw*/ 'h-[1px] bg-line-light',
  settingsListGroupSpacingMd: /*tw*/ 'mt-4',
  settingsListGroupSpacingLg: /*tw*/ 'mt-8',
  settingsListGroupSpacingXl: /*tw*/ 'mt-20',
  settingsPageSections: /*tw*/ 'flex flex-col space-y-4',
  settingsPageContent: /*tw*/ 'p-4',
  settingsPageText: /*tw*/ 'text-sm text-t1',
  settingsPageParagraphSpacing: /*tw*/ 'mb-4',
  settingsPageEmphasisText: /*tw*/ 'text-sm font-medium text-t1',
  settingsPageSubsections: /*tw*/ 'flex flex-col space-y-2',
  settingsStatusTextMuted: /*tw*/ 'text-t2',
  settingsStatusTextDanger: /*tw*/ 'text-accent-danger',
  settingsStatusState: /*tw*/ 'p-4 text-center',
  settingsDatabaseIcon: /*tw*/ 'h-5 w-5',
  formSectionStack: /*tw*/ 'flex flex-col gap-3',
  formCheckboxRow: /*tw*/ 'flex items-center gap-2 px-3',
  formCheckbox: /*tw*/ 'h-4 w-4 text-primary',
  formHintText: /*tw*/ 'text-sm text-t2',
  formLinkText: /*tw*/ 'mx-1 text-primary text-text-link',
  formPrimaryButton:
    /*tw*/ 'mt-6 w-full px-4 py-3 rounded-full bg-brand font-medium text-white disabled:opacity-50 hover:bg-brand-dark focus:outline-none',

  // font-size 14px
  baseButtonStyle: /*tw*/ 'flex items-center justify-center text-center rounded-full w-full',
  fabIcon: /*tw*/ 'size-6',
  inboxDropZone:
    /*tw*/ 'fixed bottom-20 left-4 h-12 bg-brand rounded-full flex items-center justify-center text-white transition-all duration-200',
  inboxDropZoneExpanded: /*tw*/ 'w-32',
  inboxDropZoneCollapsed: /*tw*/ 'w-12',
  inboxDropZoneVisible: /*tw*/ 'opacity-100',
  inboxDropZoneHidden: /*tw*/ 'opacity-60',
  inboxDropZoneLabel: /*tw*/ 'ml-1 text-sm whitespace-nowrap',
  lastPlacementPlaceholder: /*tw*/ 'h-10 rounded opacity-0',
  popupActionDescription: /*tw*/ 'text-sm text-t3 mb-2',
  baseButtonDisabledStyle: /*tw*/ 'opacity-50 cursor-not-allowed',
  buttonSizeLargeStyle: /*tw*/ 'h-11 text-base',
  buttonShapeDefaultStyle: /*tw*/ 'bg-brand text-white hover:opacity-90',
  buttonShapeLightStyle: /*tw*/ 'border border-line-bold border-thin text-t2 hover:opacity-90',

  // HomePageProjectItem styles (matching Vue HomeProjectItem spec)
  homeProjectItemRoot: /*tw*/ 'flex items-start py-3.5 px-4 gap-3',
  homeProjectItemCheckboxContainer: /*tw*/ 'h-6 flex items-center text-t3',
  homeProjectItemContent: /*tw*/ 'flex-1 flex flex-col gap-0.5 min-w-0',
  homeProjectItemTitleRow: /*tw*/ 'flex items-center gap-1.5 min-w-0',
  homeProjectItemTitle:
    /*tw*/ 'min-w-0 overflow-hidden text-ellipsis whitespace-nowrap text-base leading-6 font-medium transition-all duration-200',
  homeProjectItemTitleCompleted: /*tw*/ 'line-through text-t3',
  homeProjectItemTitleCanceled: /*tw*/ 'text-t3',
  homeProjectItemTitleNormal: /*tw*/ 'text-t1',
  homeProjectItemTitlePlaceholder: /*tw*/ 'text-t3',
  homeProjectItemMetaIcons: /*tw*/ 'flex items-center gap-1 text-t3 shrink-0',
  homeProjectItemMetaIconSize: /*tw*/ 'size-3.5',
  homeProjectItemDueDate: /*tw*/ 'flex items-center gap-1 text-xs font-semibold leading-6',
  homeProjectItemDueDateOverdue: /*tw*/ 'text-accent-danger',
  homeProjectItemDueDateNormal: /*tw*/ 'text-t2',
  homeProjectItemDueDateIconSize: /*tw*/ 'size-3',
  taskItemCompletionAt: /*tw*/ 'flex items-center gap-1 text-xs font-semibold leading-6 text-t3',
  taskItemCompletionAtIcon: /*tw*/ 'size-3',
  homeProjectItemEditingInput:
    /*tw*/ 'flex-1 overflow-hidden text-ellipsis whitespace-nowrap bg-transparent text-base leading-6 font-medium outline-none',
  projectHeadingItemSpacingTop: /*tw*/ 'pt-3',
  projectHeadingItemRow: /*tw*/ 'flex items-center justify-between text-base font-medium',
  projectHeadingItemArchived: /*tw*/ 'line-through opacity-50',
  projectHeadingItemEditingInput:
    /*tw*/ 'flex-1 overflow-hidden bg-transparent outline-none pl-1 tracking-wider uppercase',
  projectHeadingItemLabel:
    /*tw*/ 'flex-1 overflow-hidden text-ellipsis whitespace-nowrap bg-transparent text-t1 uppercase tracking-wider pl-1',
  projectHeadingItemMenuButton: /*tw*/ 'flex items-center justify-center size-7 text-t3 opacity-40',
  projectHeadingItemMenuIcon: /*tw*/ 'size-4',
  tagEditorInputContainer: /*tw*/ 'w-full flex flex-wrap items-center',
  tagEditorSelectedTags: /*tw*/ 'flex items-center',
  tagEditorList: /*tw*/ 'h-50 overflow-y-scroll flex flex-col',
  tagEditorSuggestionButton: /*tw*/ 'break-words w-full text-left',
  timePickerWheel: /*tw*/ 'flex-1 h-32 overflow-y-auto',
  timePickerWheelInner: /*tw*/ 'py-24',
  timePickerWheelOption: /*tw*/ 'h-8 flex items-center justify-center cursor-pointer text-lg',
  timePickerWheelOptionSelected: /*tw*/ 'text-brand font-semibold',
  timePickerWheelOptionNormal: /*tw*/ 'text-t2',
  timePickerHeader: /*tw*/ 'text-center mb-6',
  timePickerHeaderDate: /*tw*/ 'text-base text-t2 mb-2',
  timePickerHeaderTime: /*tw*/ 'text-5xl font-light text-t1 tracking-wide',
  timePickerHeaderSeparator: /*tw*/ 'text-t2 mx-1',
  timePickerWheelRow: /*tw*/ 'flex items-center mb-6 relative',
  timePickerWheelSeparator: /*tw*/ 'text-2xl text-t1 h-8 flex items-center leading-8',
  timePickerPresetSection: /*tw*/ 'mb-4',
  timePickerPresetTitle: /*tw*/ 'text-sm text-t2 mb-2',
  timePickerPresetList: /*tw*/ 'flex gap-2',
  timePickerPresetButton:
    /*tw*/ 'flex-1 py-2 px-3 rounded-lg bg-bg2 text-t1 text-sm font-medium hover:bg-bg3 transition-colors',

  // AreaHeader styles (matching Vue AreaItem spec)
  areaHeaderRoot: /*tw*/ 'flex items-center py-3.5 px-4',
  areaHeaderIconContainer: /*tw*/ 'size-6 text-t3 flex items-center justify-center mr-3 flex-shrink-0',
  areaHeaderIconSize: /*tw*/ 'size-5.5',
  areaHeaderTitle:
    /*tw*/ 'text-base leading-6 font-medium text-t1 flex-1 min-w-0 overflow-hidden text-ellipsis whitespace-nowrap',
  areaHeaderEditingInput:
    /*tw*/ 'flex-1 overflow-hidden bg-transparent text-base leading-6 text-t1 outline-none font-medium',
  areaHeaderArrowContainer: /*tw*/ 'size-6 text-t3 flex items-center justify-center',
  areaHeaderArrowSize: /*tw*/ 'size-4.5',

  // Area detail section styles (matches Vue DetailPage spec)
  areaDetailSectionHeader: /*tw*/ 'flex items-center justify-between mb-2',
  areaDetailSectionHeaderIndent: /*tw*/ 'pl-4',
  areaDetailSectionTitle: /*tw*/ 'text-sm font-medium text-t3 uppercase tracking-wide',
  areaDetailSectionCard: /*tw*/ 'bg-bg1 rounded-2xl',
  areaDetailSectionSpacer: /*tw*/ 'h-3',
  areaDetailEmptyState: /*tw*/ 'flex items-center justify-center py-8 text-sm text-t3',
  scheduledGroupCard: /*tw*/ 'ui-card-normal mb-3',

  // Home page styles
  homeCardShadow: /*tw*/ '',
};
