export const baseStyles = {
  homeMenuBackground: /*tw*/ 'bg-bg1',
  homeMenuRound: /*tw*/ 'rounded-md',
  homeMenuItemPadding: /*tw*/ 'px-3 py-2',
  homePageItemGap: /*tw*/ 'gap-2',
  homeMenuNumberColor: /*tw*/ 'text-sm font-medium text-t3',
  homeMenuDueTaskNumberColor: /*tw*/ 'text-sm font-medium text-white bg-accent-danger rounded-full h-4 min-w-4',
  homeMenuIconStyle: /*tw*/ 'w-5 h-5 text-brand',

  statCardContainer: /*tw*/ 'grid grid-cols-2 gap-3',
  statCardRoot: /*tw*/ 'px-4 pt-4.5 pb-4 flex flex-col gap-3.5 ui-card-glass',
  statCardHeader: /*tw*/ 'flex justify-between items-start',
  statCardIconContainer: /*tw*/ 'size-9 rounded-xl flex items-center justify-center',
  statCardIcon: /*tw*/ 'size-4.5',
  statCardCountContainer: /*tw*/ 'flex items-baseline gap-2 text-xl font-semibold',
  statCardOverdueCount: /*tw*/ 'text-accent-danger',
  statCardCount: /*tw*/ 'text-t2',
  statCardLabel: /*tw*/ 'text-sm text-t2',

  screenEdgePadding: /*tw*/ 'px-3',

  bottomMenuHeight: /*tw*/ 'h-11',
  bottomMenuBorder: /*tw*/ 'border-t border-line-light',
  bottomMenuTextNormal: /*tw*/ 'text-t2',
  bottomMenuTextActive: /*tw*/ 'text-brand',
  bottomMenuTextInactive: /*tw*/ 'text-t3',

  listItemRound: /*tw*/ '',
  listItemDraggedBackground: /*tw*/ 'bg-bg3',

  pageBackground: /*tw*/ 'bg-bg2',
  listItemBackground: /*tw*/ 'bg-bg1',
  listItemEditingBackground: /*tw*/ 'bg-bg1',

  itemRound: /*tw*/ 'rounded-md',

  headerBackground: /*tw*/ 'bg-bg2',
  headerRoot: /*tw*/ 'w-full h-15 px-5 py-3 relative',
  headerLeftContainer: /*tw*/ 'flex gap-2 absolute left-5.5 top-1/2 -translate-y-1/2',
  headerRightContainer: /*tw*/ 'flex gap-2 absolute right-5 top-1/2 -translate-y-1/2',
  headerTitle: /*tw*/ 'text-base font-medium text-t1 absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2',
  headerActionButton:
    /*tw*/ 'size-9 flex items-center justify-center border-none bg-bg1 cursor-pointer rounded-full shadow-soft text-t2',
  headerActionButtonIcon: /*tw*/ 'size-5 flex items-center justify-center',

  taskItemGroupRound: /*tw*/ 'rounded-md',
  taskItemGroupBackground: /*tw*/ 'bg-bg1',
  taskItemGroupHeaderPadding: /*tw*/ 'pt-2',
  taskItemGroupTopRound: /*tw*/ 'rounded-t-lg',
  taskItemGroupBottomRound: /*tw*/ 'rounded-b-lg',

  taskItemGroupPaddingBottomWhenDragging: /*tw*/ 'pb-11',

  taskItemHeight: /*tw*/ 'h-11',
  taskItemPaddingX: /*tw*/ 'px-3',
  taskItemPlaceholderColor: /*tw*/ 'text-t3',
  taskItemGap: /*tw*/ 'gap-2',
  taskItemIconSize: /*tw*/ 'size-5 flex-shrink-0 flex items-center justify-center',

  taskItemEditingRound: /*tw*/ 'rounded-md',
  taskItemEditingShadow: /*tw*/ 'shadow-sm',

  taskItemOverlayBackground: /*tw*/ 'bg-bg1',
  taskItemOverlayRound: /*tw*/ 'rounded-md',
  taskItemOverlayShadow: /*tw*/ 'inset-shadow-sm shadow-sm',

  taskItemDraggingRound: /*tw*/ 'rounded-md',

  pageContentPaddingX: /*tw*/ 'px-3',
  pageContentPaddingY: /*tw*/ 'pb-15',

  overlayBackground: /*tw*/ 'bg-black',
  overlayBackgroundOpacity: /*tw*/ 'opacity-50',
  overlayAnimationDuration: /*tw*/ 'duration-250',
  actionSheetPadding: /*tw*/ 'p-4 pt-0',
  actionSheetRound: /*tw*/ 'rounded-t-lg',
  actionSheetBorder: /*tw*/ '',
  actionSheetBackground: /*tw*/ 'bg-bg2',

  actionSheetActionGroupRound: /*tw*/ 'rounded-lg',
  actionSheetActionGroupBackground: /*tw*/ 'bg-bg1',
  actionSheetActionGroupItemPadding: /*tw*/ 'p-4',
  actionSheetActionGroupItemGap: /*tw*/ 'gap-2',
  actionSheetContentBorder: /*tw*/ '',

  tagEditorContainerBackground: /*tw*/ 'bg-bg1',
  tagEditorSelectedTagColor: /*tw*/ 'text-brand',
  tagEditorInputTextColor: /*tw*/ 'text-t1',
  tagEditorSuggestionBackground: /*tw*/ 'bg-bg1',
  tagEditorSuggestionTextColor: /*tw*/ 'text-t1',
  tagEditorCreateTagTextColor: /*tw*/ 'text-brand',
  tagEditorContainerPadding: /*tw*/ 'px-4 py-2',
  tagEditorContainerRound: /*tw*/ 'rounded-lg',
  tagEditorSuggestionPadding: /*tw*/ 'px-4 py-2',
  tagEditorSuggestionRound: /*tw*/ 'rounded-lg',
  tagEditorTextSize: /*tw*/ 'text-sm',
  tagEditorSmallGap: /*tw*/ 'gap-2',
  tagEditorHeightDefault: /*tw*/ 'h-11',
  tagEditorMinHeightDefault: /*tw*/ 'min-h-11',

  datePickerDayCellHeight: /*tw*/ '56',
  datePickerMonthHeaderHeight: /*tw*/ '40',
  datePickerGapHeight: /*tw*/ '4',
  datePickerItemHeight: /*tw*/ '0',
  datePickerDayButtonHeight: /*tw*/ 'h-14',
  datePickerDayButtonRound: /*tw*/ 'rounded-lg',
  datePickerDaySelectedBackground: /*tw*/ 'bg-brand',
  datePickerDaySelectedTextColor: /*tw*/ 'text-white',
  datePickerTodayTextColor: /*tw*/ 'text-brand',
  datePickerHeaderBackground: /*tw*/ 'bg-bg3',
  datePickerHeaderPadding: /*tw*/ 'py-2 -mx-4 px-4',
  datePickerWeekdayTextColor: /*tw*/ 'text-t1',
  datePickerWeekdayTextSize: /*tw*/ 'text-sm',
  datePickerBackground: /*tw*/ 'bg-bg1!',
  datePickerContentPadding: /*tw*/ 'px-4',
  datePickerTitlePadding: /*tw*/ 'px-6',
  datePickerActionSheetPadding: /*tw*/ 'px-0!',

  fabButton: /*tw*/ 'size-14 bg-brand rounded-full flex items-center justify-center z-[1000] text-white',

  taskDetailBottomActionStyle: /*tw*/ 'flex items-center justify-center size-9 rounded-lg  text-t2',
  taskDetailBottomActionIconStyle: /*tw*/ 'size-5',

  infoItemRound: /*tw*/ 'rounded-md',
  infoItemPadding: /*tw*/ 'py-1.5 px-2',
  infoItemMargin: /*tw*/ 'mb-1.5',
  infoItemGap: /*tw*/ 'gap-2',
  infoItemIconColor: /*tw*/ 'text-t2',
  infoItemTextColor: /*tw*/ 'text-t1',
  infoItemDeleteIconColor: /*tw*/ 'text-t3',
  infoItemIconSize: /*tw*/ 'size-4',
  infoItemTextSize: /*tw*/ 'text-sm',
  infoItemDeleteIconSize: /*tw*/ 'size-4',
  infoItemGroupGap: /*tw*/ 'gap-0',
  infoItemGroupBackground: /*tw*/ 'bg-bg1',
  infoItemGroupRound: /*tw*/ 'rounded-lg',
  itemItemMinHeight: /*tw*/ 'min-h-10',
  editingTaskSubtaskContainerBackground: /*tw*/ 'bg-bg2',
  editingTaskSubtaskPadding: /*tw*/ 'px-2',
  editingTaskSubtaskContainerRound: /*tw*/ 'rounded-lg',
  editingTaskSubtaskContainerMargin: /*tw*/ 'mb-2 mt-1.5',
  editingTaskSubtaskContainerSpacing: /*tw*/ 'space-y-0.5',

  createTaskSubtaskContainerBackground: /*tw*/ 'bg-bg2',
  createTaskSubtaskContainerPadding: /*tw*/ 'px-2',

  createTaskToolbarStyle: /*tw*/ 'size-10 bg-bg1 rounded-lg flex items-center justify-center text-t2',
  createTaskToolbarIconStyle: /*tw*/ 'inline-flex items-center justify-center size-5',
  createTaskToolbarGap: /*tw*/ 'gap-2',
  metaDataBackground: /*tw*/ 'bg-bg1',
  metaDataGap: /*tw*/ 'gap-2',
  metaDataPadding: /*tw*/ 'p-2',
  metaDataRound: /*tw*/ 'rounded-lg',

  inputItemStyle: /*tw*/ 'bg-bg1 rounded-lg focus:outline-none px-3 py-2 w-full border-0 text-base',
  textAreaItemStyle: /*tw*/ 'bg-bg1 rounded-lg focus:outline-none px-3 py-2 w-full border-0 text-sm',
  itemEditTaskNotesTextAreaStyle:
    /*tw*/ 'bg-bg1 rounded-lg focus:outline-none px-0 py-0 w-full border-0 text-sm text-t2',

  createTaskPageStyle: /*tw*/ 'min-h-dvh flex flex-col gap-2 bg-bg2 text-t1',
  createTaskPageHeaderStyle:
    'flex justify-between items-center border-b border-line-regular flex-shrink-0 safe-top sticky top-0 bg-bg2',
  createTaskPageButtonStyle: /*tw*/ 'text-sm h-12 font-medium',
  createTaskPageConfirmButtonColor: /*tw*/ 'text-brand',
  createTaskPageCancelButtonColor: /*tw*/ 'text-t2',
  createTaskPageTitleStyle: /*tw*/ 'text-base font-semibold text-t1 h-12 flex items-center',
  createTaskPageContentGap: /*tw*/ 'gap-2',

  tabbarBackground: /*tw*/ 'bg-bg1',
  tabbarHeight: /*tw*/ 'h-10',
  tabbarRound: /*tw*/ 'rounded-lg',
  tabbarItemWidth: /*tw*/ 'w-24',
  tabbarItemTextSize: /*tw*/ 'text-sm',
  tabbarItemTextColorActive: /*tw*/ 'text-brand',
  tabbarItemTextColorInactive: /*tw*/ 'text-t2',
  tabbarItemFontWeight: /*tw*/ 'font-medium',
  tabbarIndicatorWidth: /*tw*/ 'w-4',
  tabbarIndicatorHeight: /*tw*/ 'h-0.5',
  tabbarIndicatorMarginTop: /*tw*/ 'mt-1',
  tabbarIndicatorRound: /*tw*/ 'rounded-full',
  tabbarIndicatorColorActive: /*tw*/ 'bg-brand',
  tabbarIndicatorColorInactive: /*tw*/ 'bg-transparent',

  projectAreaSelectorContainer: /*tw*/ 'h-50 overflow-y-scroll flex flex-col space-y-2',
  projectAreaSelectorInputContainer: /*tw*/ 'bg-bg1 rounded-md px-3 py-2 text-t1 h-11 w-full flex items-center',
  projectAreaSelectorInput: /*tw*/ 'flex-1 min-w-40 focus:outline-none bg-transparent text-sm',
  projectAreaSelectorItem:
    /*tw*/ 'bg-bg1 rounded-md px-3 py-2 text-t1 break-words w-full text-left flex items-center gap-2',
  projectAreaSelectorItemIcon: /*tw*/ 'size-5 text-t3',
  projectAreaSelectorSubItemPadding: /*tw*/ 'pl-4',
  projectAreaSelectorTextSize: /*tw*/ 'text-sm',
  projectAreaSelectorContentGap: /*tw*/ 'space-y-2',

  switchUncheckedBackground: /*tw*/ 'bg-bg2',
  switchCheckedBackground: /*tw*/ 'bg-brand',
  switchInnerBorder: /*tw*/ '',
  switchOuterBorder: /*tw*/ '',

  dialogBorder: /*tw*/ '',

  // SettingsListItem styles
  settingsListItemRoot:
    /*tw*/ 'flex items-center justify-between py-3.5 px-4 cursor-pointer transition-colors duration-200',
  settingsListItemIconContainer: /*tw*/ 'mr-4 shrink-0 size-6',
  settingsListItemIconDanger: /*tw*/ 'text-accent-danger',
  settingsListItemIconNormal: /*tw*/ 'text-t2',
  settingsListItemContent: /*tw*/ 'flex flex-col gap-0.5 flex-1 min-w-0',
  settingsListItemTitle: /*tw*/ 'text-base font-medium',
  settingsListItemTitleDanger: /*tw*/ 'text-accent-danger',
  settingsListItemTitleNormal: /*tw*/ 'text-t1',
  settingsListItemDescription: /*tw*/ 'text-xs text-t2',
  settingsListItemCheckContainer: /*tw*/ 'size-5 flex items-center justify-center',
  settingsListItemCheckIcon: /*tw*/ 'text-brand',
  settingsListItemCheckIconSize: /*tw*/ 'size-4.5',
  settingsListItemNavContainer: /*tw*/ 'flex items-center',
  settingsListItemNavLabel: /*tw*/ 'text-xs text-t3 mr-1',
  settingsListItemNavIcon: /*tw*/ 'size-4 text-t3',
  settingsListItemLabelText: /*tw*/ 'text-xs text-t3',
  settingsListItemButtonRoot: /*tw*/ 'flex items-center py-3 px-4 cursor-pointer transition-colors duration-200',
  settingsListItemButtonAlignLeft: /*tw*/ 'justify-start',
  settingsListItemButtonAlignRight: /*tw*/ 'justify-end',
  settingsListItemButtonAlignCenter: /*tw*/ 'justify-center',
  settingsListItemButtonText: /*tw*/ 'text-base font-medium',
  settingsListItemButtonTextDanger: /*tw*/ 'text-accent-danger',
  settingsListItemButtonTextPrimary: /*tw*/ 'text-brand',

  // SettingsListGroup styles
  settingsListGroupRoot: /*tw*/ 'flex flex-col w-full',
  settingsListGroupTitle: /*tw*/ 'text-sm text-t2 ml-4 pb-3',
  settingsListGroupContainer: /*tw*/ 'flex flex-col rounded-2xl overflow-hidden bg-bg1 shadow-soft',
  settingsListGroupSubtitle: /*tw*/ 'text-xs text-t3 ml-4 pt-2',
  settingsListGroupDivider: /*tw*/ 'h-[1px] bg-line-light',

  // font-size 14px
  baseButtonStyle: /*tw*/ 'flex items-center justify-center text-center rounded-full w-full',
  baseButtonDisabledStyle: /*tw*/ 'opacity-50 cursor-not-allowed',
  buttonSizeLargeStyle: /*tw*/ 'h-11 text-base',
  buttonShapeDefaultStyle: /*tw*/ 'bg-brand text-white hover:opacity-90',
  buttonShapeLightStyle: /*tw*/ 'border border-line-bold border-thin text-t2 hover:opacity-90',
};
